USE [master]
GO

/****** Object:  Database [puntodeventa]    Script Date: 20/05/2022 08:11:54 p. m. ******/
CREATE DATABASE [puntodeventa]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'puntodeventa', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\puntodeventa.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'puntodeventa_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\puntodeventa_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [puntodeventa].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [puntodeventa] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [puntodeventa] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [puntodeventa] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [puntodeventa] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [puntodeventa] SET ARITHABORT OFF 
GO

ALTER DATABASE [puntodeventa] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [puntodeventa] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [puntodeventa] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [puntodeventa] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [puntodeventa] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [puntodeventa] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [puntodeventa] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [puntodeventa] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [puntodeventa] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [puntodeventa] SET  DISABLE_BROKER 
GO

ALTER DATABASE [puntodeventa] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [puntodeventa] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [puntodeventa] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [puntodeventa] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [puntodeventa] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [puntodeventa] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [puntodeventa] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [puntodeventa] SET RECOVERY FULL 
GO

ALTER DATABASE [puntodeventa] SET  MULTI_USER 
GO

ALTER DATABASE [puntodeventa] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [puntodeventa] SET DB_CHAINING OFF 
GO

ALTER DATABASE [puntodeventa] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [puntodeventa] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [puntodeventa] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [puntodeventa] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [puntodeventa] SET QUERY_STORE = OFF
GO

ALTER DATABASE [puntodeventa] SET  READ_WRITE 
GO

